language: node_js
node_js: 
  - "stable"

install:
  - npm install
cache:
  directories:
    - "node_modules"

services:
  - mongodb

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'