language: node_js
node_js: 
  - "stable"

install:
  - npm install
cache:
  directories:
    - "node_modules"
services:
- mongodb

#notifications:
#  slack:
#    rooms:
#      - ifts16workspace:5iJkQ3l5dhBtFImJ01PNAtku#seminario

notifications:
  slack: ifts16workspace:AH2sLmsNN2siKON8WbTs4prv